### PR TITLE
Add branch alias on dev-master

### PR DESCRIPTION
**Pull request by fredtro**
Please provide branch alias or stable releases to be able to depend on the package.

### CODE REVIEW

**Comment by dpfaffenbauer** [comment]
I could create a release 1.0.0 as well if that helps?

**Comment by fredtro** [comment]
would be fine too. thank you.

Freundliche Grüsse
Frederik Trostorf

ongoing GmbH
Kommunikation & Internet
Hinterbergstrasse 34
6330 Cham
Telefon: 041 783 12 70
E-Mail: frederik.trostorf@ongoing.ch


2018-01-10 14:11 GMT+01:00 Dominik <notifications@github.com>:

**Comment by dpfaffenbauer** [comment]
alright, 1.0.0 has been released, I'll still merge this PR as it makes totally sense.

**Comment by dpfaffenbauer** [comment]
thanks @fredtro

**Pull request merged**
