### PR TITLE
feature: Add optional params "uppReturnMaskedCC" and "useAlias" to obtain additional data from purchase request

### PR DESCRIPTION
**Pull request by fredtro**
Hi there

Me again 😀  I just need to request some additional data to implement Token billing.

Atm i am working on a Symfony 3 Bundle to use Datatrans in JMSPaymentCoreBundle. Sooo perhaps i will create some more pull requests in the future. 

Cheers

### CODE REVIEW

**Comment by dpfaffenbauer** [comment]
working with symfony 3 and ominpay is a huge problem. Omnipay v2 (which datatrans uses) is not compatible with symfony > 2. ominpay v3 is already in work, but still not finished....

**Comment by fredtro** [comment]
sure, i've read about it on the omnipay page. My fault, i'm working on a symfony2 implementation.

**Comment by dpfaffenbauer** [comment]
so is this ready?

**Comment by fredtro** [comment]
Not yet. I have finished "normal" cc payment process, next step is token billing. I will continue working on it end of this or next week. I can notify you when i am finished, if you like to.

**Comment by dpfaffenbauer** [comment]
yes please

**Comment by fredtro** [comment]
Pls let me know if you will/will not accept my pull request, or if i have to improve, change or explain things.
regards

**Comment by dpfaffenbauer** [comment]
I will merge it if it is an improvement for the library. Please continue and explain why and what you are doing, alright?

**Comment by fredtro** [comment]
Ok, do you know what alias/token billing is?You can find infos here: https://www.datatrans.ch/alias-tokenization or Chapter 5 of https://admin.sandbox.datatrans.com/showcase/doc/Technical_Implementation_Guide.pdf.

Basically its about persisting credit card data as a token. Therefor you can use those 2 parameters from the pull request.  By using "uppReturnMaskedCC=yes" you will receive a masked credit card number (like this 1234 *** *** *** 3424). Mostly persisted by client applications to show user in a user backend for example. Its more about displaying data, and not really mandatory for token billing.

By using useAlias=yes in a request, datatrans will persist credit card data for you (because in most cases its not PCI compliant to persist them as a merchant) and return a unique alias/token. This alias/token can be used for further transactions. In those cases user dont has to input CC data again.

**Comment by dpfaffenbauer** [comment]
Sounds good. Come back to me when this is finished, ok? :)

Thank you very much 🍻

**Pull request closed without merging**
